[basic]
host = "0.0.0.0"
port = 18090
ssl-key = ""
ssl-cert = ""
repos-path = "/repos"
cache-size-limit = ""
cache-clean-strategy = "LRU"
hf-scheme = "https"
hf-netloc = "huggingface.co"
hf-lfs-netloc = "cdn-lfs.huggingface.co"
mirror-scheme = "http"
mirror-netloc = "0.0.0.0:18090"
mirror-lfs-netloc = "0.0.0.0:18090"
mirrors-path = ["./mirrors_dir"]
