kind: ConfigMap
apiVersion: v1
metadata:
  name: olah-config
  namespace: olah
  labels:
    app: olah
data:
{{- $files := .Files.Glob "files/*" }}
{{- range $path, $file := $files }}
  {{ base $path }}: |
{{ $file | toString | indent 4 }}
{{- end }}
