name: Release Charts

on:
  push:
    branches:
    - main
    paths:
    - .github/workflows/chart-releaser.yaml
    - olah/**

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - name: Run Chart Releaser
      run: |
        curl -LO https://raw.githubusercontent.com/surajssd/llm-k8s/96d8571889ae1177ff325d04b6b2c8f78202d0d8/scripts/hack/chart-releaser.sh
        bash ./chart-releaser.sh --charts-dir ./ --owner surajssd --repo k8s-hf-mirror --skip-existing
      env:
        CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
